export * from "./doctorValidations";
export * from "./assessmentsValidations";
export * from "./adminValidations";
export * from "./categoryValidations";
export * from "./departmentValidations";
export * from "./postValidations";
export * from "./tagValidations";
export * from "./workshopValidations";
export * from "./clientValidations";
