export const PERMISSION_DEFINITIONS = [
  { key: "appointments.read", description: "Read appointments" },
  { key: "appointments.write", description: "Create and update appointments" },
  { key: "appointments.delete", description: "Delete appointments" },
  { key: "clients.read", description: "Read clients" },
  { key: "clients.write", description: "Create and update clients" },
  { key: "clients.delete", description: "Delete clients" },
  { key: "therapists.read", description: "Read therapists" },
  { key: "therapists.write", description: "Create and update therapists" },
  { key: "therapists.delete", description: "Delete therapists" },
  { key: "admins.read", description: "Read admins" },
  { key: "admins.write", description: "Create and update admins" },
  { key: "admins.delete", description: "Delete admins" },
  { key: "cms.read", description: "Read CMS content" },
  { key: "cms.write", description: "Create and update CMS content" },
  { key: "cms.delete", description: "Delete CMS content" },
  { key: "workshops.read", description: "Read workshops" },
  { key: "workshops.write", description: "Create and update workshops" },
  { key: "workshops.delete", description: "Delete workshops" },
  { key: "payments.read", description: "Read payments" },
  { key: "payments.write", description: "Create and update payments" },
  { key: "settings.read", description: "Read settings" },
  { key: "settings.write", description: "Update settings" },
] as const;

export type PermissionKey = (typeof PERMISSION_DEFINITIONS)[number]["key"];

export const ADMIN_SUB_ROLE_PERMISSIONS = {
  boss: [
    "appointments.read",
    "appointments.write",
    "appointments.delete",
    "clients.read",
    "clients.write",
    "clients.delete",
    "therapists.read",
    "therapists.write",
    "therapists.delete",
    "admins.read",
    "admins.write",
    "admins.delete",
    "cms.read",
    "cms.write",
    "cms.delete",
    "workshops.read",
    "workshops.write",
    "workshops.delete",
    "payments.read",
    "payments.write",
    "settings.read",
    "settings.write",
  ],
  receptionist: [
    "appointments.read",
    "appointments.write",
    "clients.read",
    "clients.write",
    "therapists.read",
    "payments.read",
  ],
  manager: [
    "appointments.read",
    "appointments.write",
    "appointments.delete",
    "clients.read",
    "clients.write",
    "therapists.read",
    "therapists.write",
    "payments.read",
    "payments.write",
    "settings.read",
  ],
  author: ["cms.read", "cms.write", "workshops.read", "workshops.write"],
  accountant: ["payments.read", "payments.write", "clients.read", "appointments.read"],
} as const satisfies Record<string, readonly PermissionKey[]>;

export const ROLE_PERMISSIONS = {
  THERAPIST: [
    "appointments.read",
    "clients.read",
    "therapists.read",
    "therapists.write",
    "cms.read",
  ],
  CLIENT: ["appointments.read", "clients.read", "clients.write"],
} as const satisfies Record<string, readonly PermissionKey[]>;
